"""added file field to books table

Revision ID: 05574ccf81e3
Revises: 9804a38be208
Create Date: 2025-03-07 01:26:13.963449

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '05574ccf81e3'
down_revision = '9804a38be208'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sort_demo')
    op.add_column('books', sa.Column('file', sa.String(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'file')
    op.create_table('sort_demo',
    sa.Column('num', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
